const BORDASELECIONADO = "#0E7D71"
const BGCORSELECIONADO = "#1AAE9E"
const BORDADISPONIVEL = "#7B8B99"
const BGCORDISPONIVEL = "#7B8B99"
const BORDAINDISPONIVEL = "#F7C52B"
const BGCORINDISPONIVEL = "#FBE192"

export {
  BORDASELECIONADO,
  BGCORSELECIONADO,
  BORDADISPONIVEL,
  BGCORDISPONIVEL,
  BORDAINDISPONIVEL,
  BGCORINDISPONIVEL
}